### ISSUE TITLE
run_test in grader.py not writing anything in log file

### ISSUE THREAD

**Issue by DipeshSharma25** [BilalZaib/AutoGrader#101]
```python
def run_test(out_file, target_folder, timeout):
    # chdir in main process create issue for django
    logger.debug("Changing directory ... ")
    cur_directory = os.getcwd()
    os.chdir(target_folder)
    with open(out_file, 'w') as f:
        old_stdout = sys.stdout 
        old_stderr = sys.stderr 
        sys.stdout = f
        sys.stderr = f
        import pytest
        pytest.main(['--timeout=' + str(timeout)])
        sys.stdout = old_stdout  
        sys.stderr = old_stderr 
    logger.debug("Restoring working directory ...")
    os.chdir(cur_directory)
```

 this function is not writing anything it is giving error res_line = out.splitline()[-1] is out of index after debugging, I got that if we insert a print statement after an import pytest it is writing the same thing in file with an error message. please help.
@bilalzaib @recluze @soachishti 
please help guys

**Comment by soachishti** [comment]
Hi @DipeshSharma25, Can you share more details of the error or stack trace. It would easier to debug that way.

**Comment by DipeshSharma25** [comment]
[
![Screenshot (29)](https://user-images.githubusercontent.com/60509313/75160053-63f86200-573f-11ea-80d8-e22626244f3a.png)
![Screenshot (30)](https://user-images.githubusercontent.com/60509313/75160059-68247f80-573f-11ea-934b-cc3ec9624c62.png)

](url)

**Comment by DipeshSharma25** [comment]
these errors I tried to debug it. test-results.log file is empty always

**Comment by DipeshSharma25** [comment]
@soachishti

**Comment by DipeshSharma25** [comment]
# TODO: Disable networking for submission file
    # Source: https://gist.github.com/hangtwenty/9200597e3be274c79896
    # Source: https://github.com/miketheman/pytest-socket
    #import socket
    #def guard(*args, **kwargs):
    #    raise Exception("I told you not to use the Internet!")
    #socket.socket = guard
    #os.nice()
    #os.setuid()

in this section what to do I didn't get exactly. is this a cause of the error

**Comment by soachishti** [comment]
![image](https://user-images.githubusercontent.com/922984/75216921-70b89c80-57b7-11ea-97aa-fa1aafc990ff.png)

Are you getting any thing in this directory?

**Comment by soachishti** [comment]
> # TODO: Disable networking for submission file
> ```
> # Source: https://gist.github.com/hangtwenty/9200597e3be274c79896
> # Source: https://github.com/miketheman/pytest-socket
> #import socket
> #def guard(*args, **kwargs):
> #    raise Exception("I told you not to use the Internet!")
> #socket.socket = guard
> #os.nice()
> #os.setuid()
> ```
> 
> in this section what to do I didn't get exactly. is this a cause of the error

Ignore it. This is just a commented code.

**Comment by DipeshSharma25** [comment]
no, I am not getting anything in that dictionary. if i add a print statement after that import pytest statement then that print is available in test-result.log file

**Comment by soachishti** [comment]
I am expecting assignment's zip file content there, on which pytest is executed. As this folder is empty pytest isn't generated any result.

Can you please confirm that view.py [L327] is unzipping assignment's content in the directory properly. 
 https://github.com/bilalzaib/AutoGrader/blob/40767cfc3351fde6948a4381eadabc3bf52ce8a6/AutoGrade/views.py#L327

**Comment by DipeshSharma25** [comment]
yes it is there

**Comment by soachishti** [comment]
Is pytest working in that folder?

**Comment by DipeshSharma25** [comment]
no that is a problem pytest is not working in that problem

**Comment by DipeshSharma25** [comment]
i tried to change a little code in run_studen_tests() [
![Screenshot (31)](https://user-images.githubusercontent.com/60509313/75227793-d9624200-57d4-11ea-918d-28585df25ebd.png)
then pytest worked in that folder but giving an error after testing database access is not allowed
![Screenshot (32)](https://user-images.githubusercontent.com/60509313/75227796-db2c0580-57d4-11ea-9bb1-0eb8ce56298e.png)

](url)

**Comment by DipeshSharma25** [comment]
but in run_test() pytest is not working

**Comment by DipeshSharma25** [comment]
Process Process-1: this is main error as per my debugging @soachishti

**Comment by soachishti** [comment]
This error is showing different variant of pytest. Please remove "pytest-django" and install "pytest", and try again with that.

![image](https://user-images.githubusercontent.com/922984/75232467-1b8d8280-57d9-11ea-89fa-6f60307a07c0.png)

**Comment by DipeshSharma25** [comment]
okh

**Comment by DipeshSharma25** [comment]
thanks a lot @soachishti  it worked.....
