### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#12]
Are we running on Python3? 

We're following python2 in class so it would be better if we change to python2. Don't think it should be that big of a problem since django would support both, no? 

Apologies for not mentioning this earlier.

**Comment by recluze** [comment]
@soachishti

**Comment by soachishti** [comment]
@recluze Ok, I will update the code to Python2.

**Comment by soachishti** [comment]
Resolved. @recluze 

It is working on both versions, now.

**Comment by recluze** [comment]
Had some minor issue with `urlllib`. Fixed that but if possible, please try to develop under python2 for the moment. Not a big issue though.

**Comment by soachishti** [comment]
Sure!
