### ISSUE TITLE
Add course "course-id" field too small

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#13]
Currently it's length is set to 6 characters. This needs to be a lot longer so that we can put, for instance ... cs101-f17-a (plus a few more characters just in case). 

BTW, I've moved to postgres on GPU machine and it's working fine.

**Comment by recluze** [comment]
Same goes for description field in "Add assignment". Why be so "kanjoos" with the fields? =]

**Comment by soachishti** [comment]
Increased the field length of course_id to 64 and description to 8192.
