### ISSUE TITLE
Other files field in assignment

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#14]
Need to have another field for "other_files" ... this can be multiple files ... for instance for adding a PDF or extra .py files which are needed for assignment.

**Comment by recluze** [comment]
(I'm currently assigning all issues to @soachishti but feel free to pass these on.)

**Comment by recluze** [comment]
These will only go in the assignment "download zip" ... don't need to have them come back ... but will need to have them extracted when running server-side tests (since the .py files might be needed) but we will have to take them from our server copy ... the only files that come from the student will be the "modifiable files"

**Comment by soachishti** [comment]
I will look into that.

**Comment by soachishti** [comment]
Other file functionality added. 0cf3da9016df15c9c0edcddc63c04f38fd991b77 @recluze

**Comment by recluze** [comment]
ATM, they're not included in the .zip downloaded by the student. He will need them to complete the assignment.

**Comment by soachishti** [comment]
They are included in student's .zip file and other files are copied to submission directory (from server-side copy) before running pytest.

**Comment by recluze** [comment]
Ah, right. Sorry. Was looking at the newer assignment (with no extra files).

**Comment by recluze** [comment]
Er ... actually .. just added another assignment with three files and they don't seem to show up in the .zip downloaded by student. Can you please confirm by adding another assignment?

**Comment by soachishti** [comment]
It's working with me. Have you enable permission for yourself (User Permission). I have tested it with guru and nauman and it is working on both.

**Comment by soachishti** [comment]
https://www.screencast.com/t/h49HRPE0DYpV

**Comment by recluze** [comment]
Well, it shows up fine in the backend (under Assignments) -- even after reload of the page. But when I download the assignment as a user, the `assignment3.zip` does not have the extra files. I just checked again with an older assignment. I will try again as I did get them downloaded in the first assignment once. 

I'll update when I have more info inshaallah.

**Comment by recluze** [comment]
Just checked again. It shows up in the submission folder (as in your screenshot) but does not in the student's downloaded zip file.

**Comment by soachishti** [comment]
Zip file is generated when Assignment save signal is called. If correct zip file is available in assignment folder then there should be no problem because zip file is downloaded from the same folder.

Can you check whether student panel and admin are on same ip/host. Last time I was updating Assignment on localhost and checking them on 121.52.146.108 (student's panel) :( 

Secondly are you downloading the same zip file of Assignment, you checked in back-end folder.

**Comment by recluze** [comment]
Right. So, I guess I have found a way to reproduce the bug. 

If you add an assignment and at that time add a "other file", it doesn't go in the zip file. 

But if you go back to the assignment and hit "save" again, this time it does get put in the zip. 

I guess the reason is that when you are saving the assignment, you save the assignment first (and at that time there are no "other files" since those are lower down in the hierarchy). After you save it once, the child node gets created and next save creates the proper zip.

**Comment by soachishti** [comment]
It was deep :)

Resolved. 939a52e4ae0075331e6bb82bf45f768f973d74f1 

I have connected save signal to sender "OtherFile". Each time a other file is saved, it is then added (appended or rewrite) to existing assignment zip file.

**Comment by recluze** [comment]
Seems to be working fine now (even though the solution isn't too elegant since it will generate the zip after saving each 'other_file'). Maybe we can keep this open with low priority for this fix.

**Comment by soachishti** [comment]
It won't generate the zip file each time. It will append the other_file to the zip file.

If assignment is saved first time:
1) Assignment save signal generates the zip file.
2) OtherFile save signal append "other file" to existing zip file.

If Assignment is updated:
1) Assignment save signal generates the zip file (Including existing other files).
2) OtherFile save signal is NOT called for existing files. It will be called for only new files.
