### ISSUE TITLE
Assignment folder name in uploads

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#15]
The assignment folder name in `uploads` folder is problematic. Since it's called as "assignment title" with spaces replaced with `-`, we need the titles to be unique (and there is no check there for uniqueness). 

So, we either need to change the folder path to `course_id/assignment_id/` or put a check for uniqueness in the title (this one should be easier I think but only if we make a composite key on course and assignment title since we can have the same name in different courses). Not sure. You can think about it.

**Comment by soachishti** [comment]
Resolved using composite key. 29a03ba19471c25240d1d04e6f34760cf5e323eb

**Comment by recluze** [comment]
Seems fine now. (Can't change the assignment title though but let's leave that for now...)
