### ISSUE TITLE
Configuration of SMTP Email Service is required

### ISSUE THREAD

**Issue by bilalzaib** [BilalZaib/AutoGrader#16]

**Comment by recluze** [comment]
Can we make it so that signup requires email verification? (To ensure that if the student registers with an ID, they actually own that email.)

**Comment by soachishti** [comment]
@BilalZaib

**Comment by bilalzaib** [comment]
@soachishti 
Done with signup email verification but didn't push changes

**Comment by soachishti** [comment]
Create a branch of that code, push that branch and start a pull request.

git add .
git commit -m "Changes"
git checkout -b SignupVerification
git push origin SignupVerification

Logon to GitHub and start a pull request.

@BilalZaib

**Comment by soachishti** [comment]
SMTP settings are added (Mailgun). #21 

You will have to install following modules `pip install django-anymail[mailgun]`

"From" section of email for "Password Reset" and "Sign Up Invitation" will be p146011@nu.edu.pk. It is limited by Mailgun. However it can be changed but that new email need to be enabled from Mailgun online account settings.

@BilalZaib @recluze

**Comment by recluze** [comment]
Umm.. why are we using mailgun? What's wrong with local SMTP (other than the fact that it will most probably land in their SPAM folder ... but that can be taken care of easily). Not saying we shouldn't do this. Just asking.

**Comment by soachishti** [comment]
In most cases local SMTP doesn't work, you can take example of my mine. If we move to web hosting provider they have switched SMTP to paid option for example GoDaddy.

However we can use Google and Outlook SMTP server for delivering emails. I have been using Mandrill and Mailgun for quiet long a ago that is why I selected this service.

**Comment by recluze** [comment]
I haven't had any issues with local mail sending but I guess it can't hurt to use Mailgun. At the very least, we'll solve the issue of mail going to the spam folder with this. Let's keep it.

**Comment by recluze** [comment]
Tried signing up with user's email `recluze` on the gmail domain... Got this error. I suppose we can go ahead and remove the email verification for now so that students can start using the system until we figure out how to handle verification. 

![screen shot 2017-09-04 at 9 01 13 pm](https://user-images.githubusercontent.com/289851/30033380-5871a372-91b4-11e7-8eb4-672f143c40ad.png)

**Comment by soachishti** [comment]
#30 

Added Outlook SMTP.

**Comment by recluze** [comment]
Works. Please send me the updated password through email and close this out please. Thanks.

**Comment by soachishti** [comment]
Closing this issue... Sent the new settings.py file to your email address.
