### ISSUE TITLE
Fix pytest fail error

### ISSUE THREAD

**Issue by soachishti** [BilalZaib/AutoGrader#2]

**Comment by soachishti** [comment]
Resolved this issue by using multiprocessing for running pytest. ee7452495db82bcc28c5aa8294255bb0044f69f6

Also solved pytest timeout issue by terminating process (multiprocessing).

@recluze 

Note: we might get 100s of processes generated when student submits assignment. But there will the timeout with each process.

**Comment by recluze** [comment]
Can you explain why we might have 100s of processes? Is this for one submission or for different ones? (Since we can expect only a few submissions at any given time...)

**Comment by soachishti** [comment]
We have 175 students who will be sending the Submission. We can expect high number of processes when due date is near. 

But we will see when something happen.

**Comment by recluze** [comment]
Made a fix in 22b6c51b45 related to this.

**Comment by recluze** [comment]
Been thinking about this. It's not a big issue if students get a few "busy" signals during high load but we need to ensure the system degrades gracefully in such cases. At the very least, we shouldn't get any incorrect scoring done.

**Comment by soachishti** [comment]
They won't receive the busy signal. They will get timeout message for their correct solution because this is how OS behave when CPU is at 100%. Student program will die (timeout) in scheduler :)

**Comment by recluze** [comment]
Yes, I know but you never know what might happen with a busy OS. I'm just worried since we have 0 checks in place for this. But anyway, I doubt the students will be able to stress test our machine. We'll cross that bridge if and when we get to it. 

Closing this for now.
