### ISSUE TITLE
Percent field in submission model

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#28]
Let's get rid of the percent field and just compute `score` dynamically. I think this is causing some issues in the reports. 

https://github.com/BilalZaib/AutoGrader/blob/1bc69c7d1d07707d09760e016a01fa4fcce85614/AutoGrade/models.py#L111

**Comment by soachishti** [comment]
#29

**Comment by soachishti** [comment]
Closing this issue, further discussion in pull request.
