### ISSUE TITLE
Separate settings file for prod

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#32]
Since it's a (really really) bad idea to publish our credentials on a public repo such as Github, we need to create a separate file for prod. In this file, we can put creds (and settings) that will be specific to prod. Then, this needs to be included in the `settings.py`. 

Create this file in the same folder as `settings.py` and import. Commit the prod settings file once (while it's empty) and then never commit it (or do this: https://stackoverflow.com/questions/4114163/how-to-tell-git-to-ignore-all-further-edit-to-a-single-file-without-removing-it) 

Please change the outlook password for the autograder sender email and send me through email. I will update the settings file in prod with it. I believe there is also a secret key or something in the settings that needs to be hidden. Also, send me that and any other things that should be hidden.

**Comment by soachishti** [comment]
#38

**Comment by soachishti** [comment]
Removed current settings.py from source code.  #38 

Password and secret key are updated and sent to you via email.
