### ISSUE TITLE
Backup script for backing up code and db together

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#35]
We're on PostgresSQL on prod. 

We need a script that will take the whole db's dump and put it in a file (timestamped). Then, it will also get the current code and put that in a zip file along with the db dump (again, timestamped). Then, upload it somewhere off-site where we can only do writes and no deletes.

**Comment by soachishti** [comment]
We can use this Django package for creating backup of media (submission/assignment) and database.

https://django-dbbackup.readthedocs.io/en/stable/installation.html

It supports PostgresSQL.

**Comment by recluze** [comment]
Looks good. Let's deploy this but ensure we can reproduce from the backup (in a sandbox).

**Comment by recluze** [comment]
But let's handle #9 first please =]

**Comment by soachishti** [comment]
@BilalZaib I will work on this.
