### ISSUE TITLE
Detecting similarity. 

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#45]
If we can integrate MOSS (http://theory.stanford.edu/~aiken/moss/) with the autograder, it should be fantastic. 

(Also, since I don't see a python submission script on their page, if you can provide one, you might get your name on the Stanford page which would be a good cred to have.) 

The way I see this working is: after the due date has passed and the instructor is viewing the report, they can click on "Analyze for similarity" button at the bottom of report. The call would collect all assignment files (rename them as `a01-p117878.py` and `a01-p119898.py` i.e. append student ID to make files unique. 

Then, it would package and submit to MOSS and set status as "running report". Once we have the report from MOSS (I believe it's HTML), we can show it to the instructor. 

This would be one of those things that you can do whenever you have time. Low priority at the moment.

**Comment by soachishti** [comment]
That is interesting, will work on this.

**Comment by soachishti** [comment]
Integrated in #46
