### ISSUE TITLE
Remove student form "get_student_latest_submissions" tuple

### ISSUE THREAD

**Issue by soachishti** [BilalZaib/AutoGrader#49]
When get_student_latest_submissions called from Assignment instance. Then it returns [(submission, student1)...]. Technically it should return submissions only. Lately I was added for report section but now it is getting confusing.

Task:
1) Remove student from `get_student_latest_submissions` returned tuple
2) Update report section
3) Update `moss_submit`, It uses `get_student_latest_submissions`.
4) Check if `get_student_latest_submissions` is used anywhere else.

**Comment by recluze** [comment]
The `assignment_aggregate_report` function in `views.py` would also be affected by this in #51
