### ISSUE TITLE
Resent Email Verification for Sign Up and Reset Password

### ISSUE THREAD

**Issue by soachishti** [BilalZaib/AutoGrader#50]
**SIGN UP - Email Verification** 
When user sign up for account then verification email is sent to their email account. But there are cases when; email are not received or they are delayed.

We can handle this like these:
Let the user "Login" after sign up without email verification. But user will get message on their screen to Verify their Email with these two options: "**Resend email**" or "**Change Email**". Without "**Email Verification**" student will not be able to submit their assignment. They will get "ERROR: Validate email first" when submitting assignments.

**RESET PASSWORD - Email Verification**
When user request for reset password, user is shown with "Email is sent" but there should be option of "**Resent Email**".

**Comment by recluze** [comment]
This would be great as I've been handling these issues manually for a few days now (mostly due to user issues but still ...)
