### ISSUE TITLE
Error in Moss submission

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#54]
I'm still getting an error on this line: https://github.com/BilalZaib/AutoGrader/blob/master/AutoGrade/models.py#L131 

I still don't see how `submission == None` in the previous line would work. Since within the `if` body, submission is `None`, calling a function on that is bound to throw an exception ...

**Comment by soachishti** [comment]
Er... that will be `!=` :)

**Comment by soachishti** [comment]
Updated that.

`if submission != None:`
