### ISSUE TITLE
Course Student List View and Unenroll Student 

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#62]
We need a view for each course that shows all enrolled students. Next to each student's row, we need a link that says "Unenroll Student". This is to remove students incorrectly enrolled in wrong sections. 

```
s = Student.objects.get(id=[STUDENT_ID])
c = c = Course.objects.get(id=[COURSE_ID]) 
s.courses.remove(c)
s.save() 
``` 

@soachishti I'll be assigning issues to you. You can pass them on to whoever is suitable.

**Comment by soachishti** [comment]
Ok
