### ISSUE TITLE
View Assignment for Instructor

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#63]
The assignment view (as seen by students) should also be visible to the instructor so that any problems in the view can be identified. 

Think we only need to put some ifs in the view assignment page to remove student email, submission password and submission history. Rest should be ok as is. 

Let's make this high priority.

**Comment by soachishti** [comment]
Got it.

What if we add "Login as Student" button against each student? This button will goes in "Student view" (Admin) and in "Course student view" #62. We will redirect instructor directly to Assignment view of student after "Login as Student" when needed . This will be more feasible for instructor to debug the problem.

What do you say?

**Comment by recluze** [comment]
That would be even better. Let's go with this.
