### ISSUE TITLE
MOSS report doesn't seem to be working 

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#64]
I've given your user on Prod staff access. Please see `/autograde/assignment_report/14`. Assignments for p176011 p176035 p176001 and p176031 are obviously copied but MOSS returns nothing. Is it a limitation of MOSS or something wrong on our end? 

(Haven't seen any non-empty MOSS report till now.)

**Comment by soachishti** [comment]
Bug resolved in moss.py, kindly update the moss.py to version 1.0.3 in prod.

I have also updated the requirements.txt file (in master).

**Comment by recluze** [comment]
Awesome. It's found all the matches I noticed earlier.
