### ISSUE TITLE
Docker version of AutoGrader

### ISSUE THREAD

**Issue by soachishti** [BilalZaib/AutoGrader#67]
I am learning Docker these days so was thinking to create Docker version of AutoGrader.

Low priority.

**Comment by recluze** [comment]
Docker is good but with something as simple (and few requirements) as Autograder, not sure if it will make sense. Anyway, good as a practice.

**Comment by soachishti** [comment]
Docker is for everything `hello-world` to huge applications. InshaAllah, I will be giving a presentation on this, soon (we planned on Friday, but it gets delayed) =]

**Comment by recluze** [comment]
Yes, I've used docker. (In fact, I added this to ITC intro but that didn't go too well I think.) I meant that it won't be of too much use for the Autograder. 

Anyway, if you can create a container for this, it might make it easier to deploy. In any case, it'll be a good "show-off" feature =]

**Comment by soachishti** [comment]
Ok, let count it as "show-off" feature =]

**Comment by soachishti** [comment]
Hyper-V killed my laptop which I installed with Docker. I have uninstalled all of them now.

Closing this issue for the reason above.

No more show-off =]
