### ISSUE TITLE
Django-guardian

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#69]
This looks very interesting for doing object-level permissions (for separating instructors for example). 

https://django-guardian.readthedocs.io/en/stable/overview.html 

This is very low priority.

**Comment by soachishti** [comment]
I looked at it earlier when working on "Assignment Report" but this requires too many changes in code compared to the queryset option which is currently used for row-level permissions of the instructor.

**Comment by recluze** [comment]
Hnn, ok. From first impression, it looked like it would require little code changes. Closing this.
