### ISSUE TITLE
Course student stats

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#87]
This is another report that we need. This one is much more important so has the highest priority among reports at the moment. Whoever is doing reports needs to do this one first (or next if already working on one). 

We need a report for each course. There should be a link in the course admin page (similar to "show report" in the assignments admin page) called "Student Stats". This opens up a new page similar to assign report view. In this, we need to do the following: 

For all students registered in this course, we need the following fields: 

`No.` 
`Student` (comes from student.__str__) 
`Roll number` 
`Assignments completed` (total number -- a completed assignment is one with at least one submission) 
`Late days remaining` 
`Average marks` (in percentage since scores might be different for each assignment) 
`Average number of submissions` (so, total number of submissions / assignments completed) 
`Average time taken` (time taken for an assignment is last submission time - open date time .. then we average over the whole course) 

If you can think of another field, please comment so we can discuss. 

**Has to be done with a separate views file and not in the main `views.py` file.** 

@soachishti Please assign forward to whoever is relevant.

**Comment by soachishti** [comment]
@BilalZaib What do you say? I think this might be simpler... you can use existing code of `assignment_report` (its table) to create this report...

**Comment by bilalzaib** [comment]
Yes its seems easy, I'll start work on it. 
There were virus issues with my laptop and now I've installed new window. It will take little time to setup all required softwares

**Comment by soachishti** [comment]
@BilalZaib OK. No problem, take your time.

**Comment by bilalzaib** [comment]
Assignments whose due date is not passed should be included in this report or not??

**Comment by soachishti** [comment]
I think it should be included; "a completed assignment is one with at least one submission".

**Comment by bilalzaib** [comment]
To calculate average marks of a student
average marks = sum_of_marks/completed_assignments or sum_of_marks/total_assignments ??
(Because there may be students who don't submit an assignment so it will be incomplete)

**Comment by bilalzaib** [comment]
What will be the formula for "Average time taken"?

**Comment by recluze** [comment]
`average marks = sum_of_marks/completed_assignments` 
`average time taken = average(time taken for an assignment is last submission time - open date time)` -- again, only for completed assignments.
