### ISSUE TITLE
Module missing in requirements.txt

### ISSUE THREAD

**Issue by recluze** [BilalZaib/AutoGrader#89]
@BilalZaib You added a module's usage in the lastest commit. Please add that to `requirements.txt` so that we know it's needed when deploying. I brought down prod due to the missing dependency just now =]

**Comment by bilalzaib** [comment]
I'm using python3...I didn't add any external module only built in modules I've used.

What is the error you are getting??

**Comment by recluze** [comment]
Hnn, python2 seems to need statistics package to be installed. I've fixed this in #90
